### ISSUE TITLE
Specifying icon prefix for icons added to library

### ISSUE THREAD

**Issue by karptonite** [FortAwesome/angular-fontawesome#10]
If an icon is added to the library with `library.add(faUser)`, we can then display them in a template with `<fa-icon="user"></fa-icon>` for solid icons. it looks like if we want to use the same icon from the "light" set, we would do `<fa-icon icon="['fal', 'user']"></fa-icon>`. 

Is this the intended syntax? It works, but is a bit clunky. It might be worth adding a separate "prefix" or "iconSet" input to handle those separately.

**Comment by devoto13** [comment]
The issue with adding `prefix` property is that there is also a `mask` property on the component, which accepts same signature, so we'll probably have to add `iconPrefix` and `maskPrefix` if we decide to go this road.

But I agree that there should be nicer way to use icons from multiple sets.

**Comment by mlwilkerson** [comment]
So @devoto13, what do you think about adding `iconPrefix` and `maskPrefix`? Would that be a nicer way?

I think a case could be made that `icon="['fal', 'user']"` is more succinct than `iconPrefix='fal' icon='user'`, but maybe it's just not as friendly?

**Comment by karptonite** [comment]
Although I proposed the change, there is a downside of the more friendly form: you can't as easily pass an icon with its prefix as a variable with the `iconPrefix` formation. At most, I'd say this should be optional, with the array notation still working.

**Comment by robmadole** [comment]
@karptonite yes, that was the same conclusion that we found with the vue-fontawesome component as well. There are advantages to the clunky 😒

**Comment by devoto13** [comment]
My main concern about adding `iconPrefix` and keeping support for array form in the `icon` property is that we'll have multiple ways to pass same information and I foresee bunch of bug reports about it... E.g. which icon this component should display?

```html
<fa-icon iconPrefix="fas" [icon]="['fal', 'user']"></fa-icon>
```

If we are going to do this, we'll need to only allow icon name to be specified in the `icon` property, which in turn will make [binding icon definition from component](https://github.com/FortAwesome/angular-fontawesome/blob/master/examples/example.component.html#L3) impossible.

<details>
  <summary>digression</summary>

In practice I always bind icon definition from the component, as it is the best approach from type safety and code assistance perspective and is the most safe way for the bundle size (at a cost of boilerplate code in the component). But I see how shared library can be useful. What I was thinking is that instead of binding string icon names we can inject FA Library into component and use it to get icon definitions. Consider:

```ts
@Component({
    selector: 'my-comp',
    template: '<fa-icon [icon]="library.fal.user"></fa-icon>'
})
class MyComp {
  constructor(public library: FALibrary) {}
}
```

It does not give any advantages of biding icon definition directly, but at least there is less punctuation characters involved in the binding :)
</details>
<br>

Given above I'm -0.1 on introducing `iconPrefix`.

Maybe we can allow binding `fal-user` as a string  instead? Than users could use it like below and component will take care about separating it into prefix and icon name?

```html
<fa-icon icon="fal-user"></fa-icon>
```

**Comment by mlwilkerson** [comment]
Especially after working on adding some better examples and explanations in #12, I lean toward _not_ adding `iconPrefix` and keeping only the array syntax like:
```
<fa-icon [icon]="['fal', 'user']"></fa-icon>
```

Keep in mind too, though, that you don't _have_ to specify the prefix at all, if you pass in an icon _object_ that knows its own prefix, which seems like what @devoto13 prefers—if I read correctly.

So, if you were to do an import like:
```
import { faUser as lightUser } from '@fortawesome/fontawesome-pro-light';
```
And make the `lightUser` object available to your template, then in your template you could do:
```
<fa-icon [icon]="lightUser"></fa-icon>
```

**Comment by mlwilkerson** [comment]
Given our discussion above, I'm going to close this now, but glad to re-open if there's more to explore here.
