### ISSUE TITLE
Feature request: Multiple icon in one fa-icon

### ISSUE THREAD

**Issue by WizardPC** [FortAwesome/angular-fontawesome#124]
### Describe the problem you'd like to see solved or task you'd like to see made easier

I'm asking myself if there is a way to achieve this with angular-fontawesome :

```
font-family: 'FontAwesome';
content: '\f1b9\00a0\f1b9';
```

With the classic font awesome css it will result in two car icon next to each other.

But i don't find a way to do it in one `fa-icon`

### Is this in relation to an existing part of angular-fontawesome or something new?

Using font-family and content in css

### What is 1 thing that we can do when building this feature that will guarantee that it is awesome?

Clean syntax

### Why would other angular-fontawesome users care about this?

If i need it, someone in the world need it too.

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?

3

### Feature request checklist

- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by devoto13** [comment]
Thank you for the feature request, however it is not something we want to support. 

It works in CSS implementation because of abuse of the implementation detail. Since `angular-fontawesome` works very differently such abuse is not possible. If you want to display multiple icons you'll have to display multiple `<fa-icon>` components, each with its own icon.

It is pretty easy to use `ngFor` to display array of icons:

```
@Component({ template: `<fa-icon [icon]="icon" *ngFor="let icon of icons"></fa-icon>` })
class FaIcons {
  icons = ['star', 'car', 'user'];
}
```

It is also pretty easy to implement a re-usable component for this if you need to do it in a lot of places.
