### ISSUE TITLE
Input title does not work in Internet Explorer

### ISSUE THREAD

**Issue by Devqon** [FortAwesome/angular-fontawesome#138]
### Describe the problem

When using an `[title]` input attribute it does not work in internet explorer. It does work when using the plain `title` attribute.

When using the input attribute, it does not render the `title` attribute on the `fa-icon` element:

```
<fa-icon [icon]="fortAwesome" title="This works in IE"></fa-icon>
<fa-icon [icon]="fortAwesome" [title]="'This does not work in IE'"></fa-icon>
```

### What did you expect?

Input title also works for IE

### Reproducible test case

Open this stackblitz in IE:
https://stackblitz.com/edit/angular-z8v4ux-dk2gxu?file=src/app/app.component.html

**NOTE**:
Not really sure if this is an issue of this library, or an angular general problem.

**Comment by devoto13** [comment]
I think it is a bit of both. In your first example Angular will pass the value to the `fa-icon` component, which will end up in the `<title>This works in IE</title>` element inside rendered SVG element. But it will also set `title` attribute on the `<fa-icon>` element. My speculation is that IE does not support the [`title`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) tag, but it works because Angular also sets `title` attribute on the component element. The later  does not happens in your second example. 

I've been arguing with somebody from the Angular team that this behaviour is inconsistent, unexpected and counter-intuitive, but they said that this is intended and they are not going to change it.

Probably the best we can do is to rename `title` property of `fa-icon` to something else (like `iconTitle`), so it won't collide with the build-in DOM property and therefore won't work in IE in both cases.

**Comment by Destreyf** [comment]
@Devqon 

I've had a similar issue where i had my own properties interfering, if your goal is just to trigger the "title" property as if it were plain HTML but are wanting to pass in a variable i would recommend doing it this way:

```html
<h1><fa-icon [icon]="fortAwesome" [attr.title]="'My awesome title'"></fa-icon> angular-fontawesome template</h1>
```

Using `[attr.title]` forcibly sets the attribute on the fa-icon element, this can be done to target any traditional HTML attribute that may have an overlapping input parameter.

**Comment by devoto13** [comment]
As said above it is an Angular intended behaviour: https://github.com/angular/angular/issues/24376. I'll rename all `title` inputs to something else to avoid a potential place to make a mistake.

As for the `title` input of the `fa-icon` it renders as https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title, which "browsers usually display ... as a tooltip". But they don't have to and IE 11 apparently doesn't.

**Comment by devoto13** [comment]
Okay, I tried to fix this based on the assumption, that `title` input is only intended to define label for assistive technologies, but not tooltip and that tooltip was an unintended side effect, but it looks more like `title` is supposed to both display a tooltip and add a11y label. Given the above I'll just ensure that `title` attribute is set using both syntaxes, which will ensure that tooltip is present in all browsers.
