### ISSUE TITLE
Contradiction in documentation regarding Tree Shaking?

### ISSUE THREAD

**Issue by raydawg2000** [FortAwesome/angular-fontawesome#150]
In the section regarding the Icon Library, this snippet is at the end:

`"You can also import entire icon styles. But be careful! Whatever you import may end up bloating your final bundle with icons you're not using."`

Further down in the documentation regarding Tree Shaking there is this:

`"Tree shaking — automatically eliminating unused icons from the final bundle—Just WorksTM"`

These 2 statements seem to contradict each other and I am wondering if the Icon Library text is left over from Pre-Angular 8 upgrade?

**Comment by devoto13** [comment]
What we mean in the first statement is that it is not possible to tree shake because it is not possible to statically identify, which icons are used or not when adding whole icon package into the library. But if you import single icon from the package it will automatically drop all others from the bundle without any extra configuration for the bundler.

E.g.

```
import { far } from '@fortawesome/free-regular-svg-icons';
library.add(far); // this will include every single regular icon in the bundle (as bundler does not now, which icons are used elsewhere)
```

```
import { faUser } from '@fortawesome/free-regular-svg-icons';
library.add(faUser); // this will drop (tree shake) everything except user icon (as it is possible to statically identify that only `faUser` symbol is imported from the package)
```

I agree that documentation can be improved here by saying that first statement is particularly related to importing whole icon package using the demonstrated syntax.
