### ISSUE TITLE
Feature request: Programming API for icons

### ISSUE THREAD

**Issue by Ionaru** [FortAwesome/angular-fontawesome#153]
### Describe the problem you'd like to see solved or task you'd like to see made easier
I want to change an icon to indicate progress during an async function.
Currently I'd need to keep an extra variable that the Angular template can check against and make different icons visible. I'd much rather talk to the icon directly.

### Is this in relation to an existing part of angular-fontawesome or something new?
I couldn't find a way to change the icon using typescript, so I think this is new.
If this is already possible then please point me in the general direction where this is documented.

### What is 1 thing that we can do when building this feature that will guarantee that it is awesome?
Use Angular's best practises for the API.

### Why would other angular-fontawesome users care about this?
They will be able to modify and change icons with code in their components.

Example 1:
```html
<fa-icon #myIcon [icon]="someIcon" (click)="doASpin(myIcon)"></fa-icon>
```

```ts
public doASpin(myIcon: FaIconComponent) {
    myIcon.spin = true;
    // Icon is now spinning, wheeeeee!

    setTimeout(() => myIcon.spin = false, 9001);
    // Let's not get too crazy.
}
```

Example 2:
```html
<fa-icon #myIcon [icon]="someIcon" (click)="changeIcon(myIcon)"></fa-icon>
```

```ts
public changeIcon(myIcon: FaIconComponent) {
    myIcon.icon = icon(someOtherIcon as IconDefinition);
}
```

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?
9 - "Tomorrow's fine too"

### Feature request checklist

- [x] This is a single feature-ish (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by devoto13** [comment]
Thanks for opening an issue @Ionaru.

The piece you're missing to get it working is to call `myIcon.ngOnChanges({})` after setting the component property to the new value. Also in your second example you rather want to do `myIcon.iconProp = someOtherIcon;`, then after doing `myIcon.ngOnChanges({})` the `fa-icon` will render an icon definition into HTML itself. But this is a dirty unsupported workaround and I would rather recommend to create a property in your component and bind it to the `fa-icon` in the template.

---

The issue is that at the moment Angular has almost no support for working with components programatically. Maybe this will change with Ivy and then we will be able to provide a good programmatic API.

Here is another issue with a related problem: https://github.com/FortAwesome/angular-fontawesome/issues/72#issuecomment-462047643.

Guess if I see one more issue around this area I'll give up and accept introducing something similar to https://github.com/FortAwesome/angular-fontawesome/pull/126. Maybe `faIcon.update({icon: faUsers, spin: true})` or something.

**Comment by Ionaru** [comment]
Will you guys be able to document the existing function and what they do?
I've seen `ngOnChanges()` in the type definitions but from the name it looks more like an event than a function that applies an update to the icon.

**Comment by devoto13** [comment]
This is an [Angular hook](https://angular.io/api/core/OnChanges), which Angular calls, when you set new values to the properties in the template. Unfortunately it is not called, when you set same properties programatically. Calling it manually is a workaround to make component render updated icon. As it is a workaround you use it at your own risk. We don't officially recommend doing this and that's why it is not documented.

**Comment by Ionaru** [comment]
With `myIcon.ngOnChanges({});` it works like a charm, thank you for the help!

I hope the functionality gets expanded by both the Angular and FontAwesome teams in the future. 👍

**Comment by toverux** [comment]
Hi! I need this too, same use case :)

I've discovered that calling `ngOnChanges` works because I'm quite used to change inputs programmatically, especially since Angular directives can't bind to inputs of the host element through `@HostBinding` (obly DOM attributes).

I'm not sure that Angular will offer an API to do that properly anytime soon as the problem is complex, and actually, using `ngOnChanges` directly is dangerous (in fact, there's even a TSLint check for that).
It works here because, very fortunately, you don't use the `changes: SimpleChanges` argument that is passed to `ngOnChanges()`.
The day it changes (because you want to optimize the re-rendering for example), my app breaks without a compile-time error. I'm already seeing it happen :D

It would be really cool if we could have a `public render(): void` method on `FaIconComponent`, that we can call to trigger the same rendering code as `ngOnChanges()` now. Then, `ngOnChanges()` can just call this `render()` method. A three-lines diff.

If one day, in the middle of a refactor, this method had to be removed, it can be done with a breaking change version, so we're aware of the change (and the project won't compile).
