### ISSUE TITLE
Dynamic append a font awesome icon in content 

### ISSUE THREAD

**Issue by Rui90** [FortAwesome/angular-fontawesome#159]
I already got the way how to use the fa-icon in order to display font awesome icons.

But I need another way to display icons in angular and I don't know if you guys provide it or even if that is possible.

So basically before angular I used for instance the following directly in the css styles:

```
    &::before {
      display: block;
      position: absolute;
      content: "\f005";
      font-family: "Font Awesome 5 pro";
      pointer-events: none;
    }

```
But now, nothing renders, and I don't know if that is possible to still be used or to override it. Any type regarding this "content" situation?

**Comment by devoto13** [comment]
No, this way of rendering icons with CSS is not possible with `angular-fontawesome`. Can you explain why you don't want/can't use `fa-icon` component in this case? Is it because you don't have access to the source code of the component, where you want to add an icon?

You can also check https://github.com/FortAwesome/angular-fontawesome/issues/72 about rendering dynamic icons using Angular facilities.

**Comment by Rui90** [comment]
@devoto13 I'm currently struggling with the stars icon for instance, because currently it shows only the border painted, but on hover or selected I've also want to paint it inside. So previously I changed the font-weight on a css modifier, but now it does not seem to work, or at least I'm not being able to achieve it

![image](https://user-images.githubusercontent.com/6035220/62708335-1a3a6b00-b9eb-11e9-8c89-d6544dc7ac70.png)

**Comment by devoto13** [comment]
This you can achieve with `fa-icon` by changing the `icon` input dynamically: 

https://stackblitz.com/edit/angular-z8v4ux-5kcr4x

**Comment by Rui90** [comment]
@devoto13  cool! thank you very much
