### ISSUE TITLE
dom.watch() causes a lot of problems in Angular 8

### ISSUE THREAD

**Issue by timohermans** [FortAwesome/angular-fontawesome#171]
### Describe the problem

I upgraded font awesome from 0.4 to 0.5 after upgrading Angular from 7 to 8. However, after upgrading to 0.5 and succesfully exchanging the old svg-core library to the new library, I noticed that every function call or directive that is triggered by change detection to cause a whole application freeze that is 

### What did you expect?

A deprecation error or something else

### Reproducible test case

https://stackblitz.com/edit/angular-5i1nix 

so I put it in a working state. If you enable `dom.watch()` in `app.module.ts`, you see that when clicking the dropdown, everything breaks

**Comment by devoto13** [comment]
`FaIconLibrary` is not designed to work with `dom.watch()`, so you'll need to add icons into both: old global library and `FaIconLibrary` (I'll update upgrading instructions with the note about it). I was actually thinking to drop support for `dom.watch()` completely in several releases as mixing MutationObserver with Angular change detection is risky (as this issue indicates). Can you describe why do you use `dom.watch()` together with `angular-fontawesome`?

The issue is that mutation observer used by `dom.watch()` triggers Angular change detection, which in turn triggers ng-bootstrap to re-position the dropdown, which modifies DOM, which triggers mutation observer used by `dom.watch()`... You got it. Infinite loop of change detection. To workaround it you can run `dom.watch()` outside of Angular zone: https://stackblitz.com/edit/angular-uapz9n. But I would rather recommend to not use `dom.watch()` together with `angular-fontawesome`.

**Comment by timohermans** [comment]
Thanks for the quick reply! Also very interesting stuff regarding how `dom.watch()` actually works.

As to why I use it: I recently joined a company that had this piece of code in the app module of the project I'm now working on. I'm not sure (yet) as to why it was actually in there 😅. I was really lucky I guess to find the culprit to be the `watch` 😊

**Comment by devoto13** [comment]
Yeah, indeed! 

Basically there is a `fontawesome-svg-core` library, which can use `MutationObserver` to replace `<i class="fas fa-user></i>` with the `<svg>` element containing the icon. `dom.watch()` controls this functionality. If you don't use  `<i class="fas fa-user></i>`, but use `<fa-icon icon="user"></fa-icon>` to render icons, then you don't need to call `dom.watch()`. 

`angular-fontawesome` also uses `fontawesome-svg-core` under the hood, but it relies on Angular change detection instead of using `MutationObserver` to render icons.

There is a bit of documentation [here](https://fontawesome.com/how-to-use/on-the-web/advanced/svg-javascript-core), but it is not very useful.

**Comment by piernik** [comment]
It turns out that I need `dom.watch()` too. I'm fetching html from server where icons can be used (`<i class="fa far-calnedar"></i>`). Maybe in `FaIconLibrary` You can provide method that will trigger checking icons in plain html, so we could manually run that function? And also You could run that proccess outside angular's zone?

**Comment by Cammeritz** [comment]
I had the same problem too.

My workaround was simply calling "dom.i2svg();" once after i fetched the html and inserted it into the dom :)

**Comment by piernik** [comment]
@Cammeritz - it's working but in that way You have to add icons to `FaIconLibrary` from `@fortawesome/angular-fontawesome` and to `library` from `@fortawesome/fontawesome-svg-core`.

New method in `@fortawesome/angular-fontawesome` will be much better.

**Comment by devoto13** [comment]
Thanks for sharing your feedback, everybody! I've been thinking about this issue for a while and I don't want to add any explicit integrations with `library`, `dom.watch()` or `dom.i2svg()` to `angular-fontawesome`. There are two reasons for this:

- The direction `angular-fontawesome` has been moving over the last year is to make `fontawesome-svg-core` its implementation detail to reduce API complexity for consumers and allow to fix some long standing issues. Adding any explicit integrations with `fontawesome-svg-core`-specific features would be a step in the opposite direction.
- From your replies it sounds like the primary use-case for this feature is to render icons in the arbitrary HTML string, which really is not specific to Angular. That's why I don't believe this feature belongs in `angular-fontawesome` library.

It is still a valid approach to install `fontawesome-svg-core` directly and use its features. I'll write a guide in the documentation on how to do this correctly. But there will be no special integrations with `angular-fontawesome`. 

PS While it may be nicer to have a special method to add icons to both libraries it does not aligns with the library direction and also it is pretty trivial to implement such helper in the application's code.
