### ISSUE TITLE
Svg element prevents parent element data-toggle

### ISSUE THREAD

**Issue by tomthebearded** [FortAwesome/angular-fontawesome#200]
Hi

I have a bootstrap 4 panel that should be collapsed with a click of a button.
This is the button:
`<button class="btn btn-link float-right" data-toggle="collapse" data-target="#collapse-inscription" aria-expanded="true"
                aria-controls="collapse-inscription" (click)="toggleInscription()">
                <fa-icon [icon]="inscription.collapsed ? faChevronDown : faChevronUp"></fa-icon>
            </button>`
The problem is that the svg element that is created in html prevents the data-toggle attribute to work.

**Comment by devoto13** [comment]
@tomthebearded There are two unlucky coincidences leading to this problem: 
- the fact that `fa-icon` destroys and re-creates an SVG element when you change the `icon` input 
- the fact that you use the regular Bootstrap JS, which Angular has no idea about

First of all you need to understand how [event bubbling works in JS](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Bubbling_and_capturing_explained). In this case you end up with 2 click handlers: on the button (which is registered by Angular) and on the `document` (which is registered by the Bootstrap to toggle the Collapse). First the handler on the button is triggered, which changes the `collapsed` property and (since Angular has no idea about Bootstrap's handler) it considers event handling to be completed and therefore triggers change detection run. During the change detection the `icon` input of `fa-icon` component is updated, which destroys the `svg` element and therefore `path` element inside `svg`, which is the event target. As event [target](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) is destroyed browser does not call any other click handlers (and therefore the Bootstrap JS Collapse handler is not triggered).

Potential solutions:
- Do not mix Angular with other JS libraries, which touch DOM, because of problem like this. Consider using [ng-bootstrap](https://ng-bootstrap.github.io/) or [ngx-bootstrap](https://valor-software.com/ngx-bootstrap/) instead.
- Delay change of of the `collapsed` property by doing something like `setTimeout(() => this.collapsed = !this.collapsed, 0)`, so Bootstrap's JS runs before the `fa-icon` is updated ([example](https://stackblitz.com/edit/angular-z8v4ux-xfqkfu?file=src/app/app.component.html)).

While it would be better for `fa-icon` to not destroy the SVG element, but update it instead it will require the full library rewrite and is not something, which will happens in the foreseeable future, so you'll have to solve this on your side.

**Comment by tomthebearded** [comment]
@devoto13  Thank you very much for your explanation.
I will consider moving to ng-bootstrap or ngx-bootstrap.

**Comment by devoto13** [comment]
@tomthebearded I hope that by now you have resolved your problem one way or the other.

I'm going to close this issue as this is an integration problem and we can't really do anything in the `angular-fontawesome` to solve it in the foreseeable future.
