### ISSUE TITLE
@FortAwesome/angular-fontawesome dependency has deprecated

### ISSUE THREAD

**Issue by Rosseyn** [FortAwesome/angular-fontawesome#201]
Error in browser log appears:

FontAwesome: Global icon library is deprecated. Consult [https://github.com/FortAwesome/angular-fontawesome/blob/master/UPGRADING.md](https://github.com/FortAwesome/angular-fontawesome/blob/master/UPGRADING.md) for the migration instructions.

**Comment by devoto13** [comment]
You see this message, because you still use global icon library, which was deprecated in the latest release. You should follow [upgrade instructions](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/upgrading/0.4.0-0.5.0.md#migrate-from-global-icon-library-to-faiconlibrary) to migrate the the `FaIconLibrary`. Do you experience any specific issues following the upgrade instructions?

**Comment by Rosseyn** [comment]
I posted this in the wrong repo, there's another one referencing that file in this repo. My bad.

**Comment by Rosseyn** [comment]
I posted this in the wrong repo, there's another one referencing that file in this repo. My bad.
