### ISSUE TITLE
solid icons in main-bundle while used in lazy loaded modules and main

### ISSUE THREAD

**Issue by thepercival** [FortAwesome/angular-fontawesome#253]
### Describe the problem
I use mostly solid icons in the main module and in lazy loaded modules. All the solid icons are located at the main-bundle(longer first load). I would like to separate the solid icons so that  the icons are in the bundle where they are used.  See the screenshot for the actual situation.

### What did you expect?
I expect the solid icons to be in the bundle where they are used

The stat size off the fortawesome-part in the main bundle is 1.22MB(22KB gzipped).
Should I use a different approach or am I doing it the wrong way? Is there a solution anyway?

![Schermafdruk van 2020-05-19 11-05-21](https://user-images.githubusercontent.com/1693544/82308077-94a80a80-99c1-11ea-89e1-9da30f03ee7b.png)

**Comment by devoto13** [comment]
I'm not a huge expert in the area, but here is my understanding. 

If you import icons as `import { icon } from "@fortawesome/fontawesome-svg-solid-icons"` then it is imported from the `index.es.js` (a file containing all Solid icons of a size 1.22MB). Webpack can not split a single file between different chunks. As long as you have at least one icon import outside of lazy loaded chunks whole FA icons module will be pulled into the main bundle. The good news is that minification process will remove all unused icons from the file, so resulting size in your bundle is only 64KB (if I interpret your screenshot correctly).

If you want to prevent some icons from ending up in the main bundle you'll probably need to use [explicit reference](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/explicit-reference.md) approach in the lazy loaded modules instead of icon library and make sure that you always import icons using deep imports, e.g. `import { icon } from "@fortawesome/fontawesome-svg-solid-icons/icon"`.

In any case, it is not an issue of `angular-fontawesome`, but rather a generic question about how Webpack/Angular build toolchain functions, which is better to be asked on StackOverflow as we try to keep this issue tracker for bug reports and feature requests.

**Comment by thepercival** [comment]
Thanks for your reply. Next time I will try stackoverflow first. If you explain it like that, it is indeed more a general-build-issue rather than an angular-fontawesome-problem. Still thanks for your effort for looking into it. I will see if the explicit approach is something I can make use of.

**Comment by devoto13** [comment]
One potential improvement, which can be done here is to update how SVG icons packages are structured to make it work without deep imports, but this needs to be taken with the FontAwesome umbrella project and may be a massive breaking change for some of the FontAwesome consumers.

**Comment by thepercival** [comment]
To have solid icons in the main-bundle and in lazy loaded modules seems a normal situation to me. A lot of angular users would profit from a better divide between the modules. I am not in the position to decide if your proposal should be excuted or not. It sound like the core of the module will be affected to do this. So this would suggest a lot of work. I think this is a great library and will follow the project activities. Keep up the good work

**Comment by devoto13** [comment]
This will provide only minor improvement over the current situation (you still have to use explicit reference or multiple libraries per lazy loaded module). So this provides only minor improvement for a very specific use case, while requiring significant amount of work from umbrella project, potentially involves breaking changes for other use cases. Also this requires a lot of discipline from the library consumers to actually be beneficial. These are the main reasons why it was not pursued before. But I'll keep track of this and bring it up to the team if situation changes.
