### ISSUE TITLE
SSR Error: Property `icon` is required for `fa-icon`/`fa-duotone-icon` components.

### ISSUE THREAD

**Issue by MurhafSousli** [FortAwesome/angular-fontawesome#255]
### Describe the problem

I have a library for share buttons which uses FA for the icons

Since I introduced the a new module [ShareIconsModule](https://github.com/MurhafSousli/ngx-sharebuttons/blob/release/v8/projects/ngx-sharebuttons/icons/src/share-icons.module.ts) to simplify importing the icons, the users of the library started gets the following error in SSR

```
> node dist/angular9-starter/server/main.js

Node Express server listening on http://localhost:4000
ERROR Error: Property `icon` is required for `fa-icon`/`fa-duotone-icon` components.
    at /Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:803477
    at FaIconComponent.ngOnChanges (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:803563)
    at FaIconComponent.wrapOnChangesHook_inPreviousChangesStorage (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1851184)
    at callHook (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1670406)
    at callHooks (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1670035)
    at executeInitAndCheckHooks (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1669408)
    at refreshView (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1713172)
    at refreshEmbeddedViews (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1713969)
    at refreshView (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1714051)
    at refreshComponent (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1729521)
ERROR Error: Property `icon` is required for `fa-icon`/`fa-duotone-icon` components.
    at /Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:803477
    at FaIconComponent.ngOnChanges (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:803563)
    at FaIconComponent.wrapOnChangesHook_inPreviousChangesStorage (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1851184)
    at callHook (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1670406)
    at callHooks (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1670035)
    at executeInitAndCheckHooks (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1669408)
    at refreshView (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1713172)
    at refreshEmbeddedViews (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1713969)
    at refreshView (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1714051)
    at refreshComponent (/Users/sousli/Desktop/angular9-starter/dist/angular9-starter/server/main.js:1:1729521)
```

**NOTE:** the library works as expected and the icons are shown but this errors is displayed in express console.

### What did you expect?

No errors in express server console

### Reproducible test case

Issue source:
https://github.com/MurhafSousli/ngx-sharebuttons/issues/453

Reproduction:
https://github.com/MurhafSousli/ngx-sharebuttons/files/4706063/angular9-starter.zip

**NOTE:**

While building the app in SSR, this warning shows up

`Warning: Entry point 'ngx-sharebuttons/icons' contains deep imports into '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faFacebookF', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faTwitter', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faRedditAlien', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faLinkedinIn', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faTumblr', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faPinterestP', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faWhatsapp', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faVk', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faFacebookMessenger', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faTelegramPlane', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faMix', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faXing', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-brands-svg-icons/faLine', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-solid-svg-icons/faSms', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-solid-svg-icons/faMinus', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-solid-svg-icons/faEllipsisH', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-solid-svg-icons/faLink', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-solid-svg-icons/faExclamation', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-solid-svg-icons/faPrint', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-solid-svg-icons/faCheck', '/Users/sousli/Desktop/angular9-starter/node_modules/@fortawesome/free-solid-svg-icons/faEnvelope'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.
`

**Comment by devoto13** [comment]
This is actually a valid error. SSR was not able to render the icons for some reason. If you disable JS in the browser you will see that page rendered on the server does not contain any icons, they only appear once JS kicks in and re-renders icons during the hydration.

I've debugged this a bit: icons are correctly added to the `IconLibrary` and the instance of icon library injected by `FaIconComponent` contains these definitions. So I'm pretty sure that bug is on your side. The error message is pointing out that you're passing `null` or `undefined` to the `icon` input during SSR. Probably [over here](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/button/src/lib/share-button.html#L23). 

I'm not very familiar with SSR and your library has a pretty complex structure, so I was not able to identify what is going wrong reasonably fast. I guess you'll have to debug the SSR bundle to figure out why this is happening and fix it on your side. I ran `ng run angular9-starter:server` and then was able to debug `dist/angular9-starter/server/main.js` as a regular Node program.

Having said that we don't have any SSR tests in `angular-fontawesome` at the moment. I'll keep this issue open to track adding such a test.

PS As for the warning it does not seem to influence this problem. However, you may consider to use imports from the entry point (e.g. `@fortawesome/free-solid-svg-icons`) instead. Angular CLI should drop any unused icons from the bundle during the production build. And the problem with deep imports is that these are CommonJS, not ES modules, so they will cause a deoptimization in module concatenation and if I understood it right will produce warnings during builds starting with Angular 10.

**Comment by MurhafSousli** [comment]
Thanks for the fast response! You are right, the warning disappeared after remove the deep imports.
And the SSR errors also disappeared by checking for the icon in the template here https://github.com/MurhafSousli/ngx-sharebuttons/pull/432/commits/bb7c69fa30b187f50348e6b9765c79764f267fbc

Thank you very much! the issue can be closed if you want!

**Comment by RodrigoQC** [comment]
Try using like the exemple of git: `https://github.com/FortAwesome/angular-fontawesome#usage`
import the icon e attributed to a variable.
In my case that was the reason.

**Comment by MurhafSousli** [comment]
I think this can be closed now, I am going to close it!
