### ISSUE TITLE
Feature request:  Versioning follow angular major versions

### ISSUE THREAD

**Issue by bovandersteene** [FortAwesome/angular-fontawesome#282]
### Describe the problem you'd like to see solved or task you'd like to see made easier

It would be easier if the package follow the major angular version for version support:

f.e.
- 10.x.x supports angular 10
- 11.x.x supports angular 11

So we don't need to search in the release notes, but we can see it immediately if we look at the package.json file
 
### Feature request checklist

- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by devoto13** [comment]
Thanks for the suggestion. I see how this may be useful. The only concern I have is as to what happens if we need to release another major release outside of Angular lifecycle. We'll consider doing this when we're ready to release a stable 1.0.0. 

There is another open issue regarding the confusing versioning: #263. I'll close this one to keep discussion in one place. Please add a comment to #263 if you have any other thoughts.

In the meantime you can prominently see the compatibility in the [README](https://github.com/FortAwesome/angular-fontawesome#compatibility-table), we announce such changes in the release notes as you've mentioned (I believe people read them before updating 😄) and also consumers will get a peer dependency warning if they install a wrong version.
