### ISSUE TITLE
ngcc failed to run on @fortawesome/angular-fontawesome@0.9.0 in Stackblitz

### ISSUE THREAD

**Issue by MurhafSousli** [FortAwesome/angular-fontawesome#323]
### Describe the problem

Once I install @fortawesome/angular-fontawesome@0.9.0 in a new stackblitz it shows the following error

`Error in ~/src/main.ts ngcc failed to run on @fortawesome/angular-fontawesome@0.9.0.`

### What did you expect?

I expect the stackblitz to work with the latest version 0.9.0

### Reproducible test case

Just create a new stackblitz and install `@fortawesome/angular-fontawesome@0.9.0`, you will get the error, here is a reproduction: https://stackblitz.com/edit/angular-ivy-tktazp?file=src%2Fapp%2Fapp.module.ts

**Comment by devoto13** [comment]
Given that that `ngcc` works locally with `angular-fontawesome` and that [other libraries](https://github.com/stackblitz/core/issues/1227) have the same issue on Stackblitz, the problem is likely on their side. Unfortunately, there is not much we can do here until Stackblitz produced a useful error message which we can act upon. I would suggest tracking https://github.com/stackblitz/core/issues/1364 for future updates from their side.

I'll keep this issue open as we should consider migration to another platform unless Stackblitz addresses the problem.
