### ISSUE TITLE
"ChevronLeft" turns into "times" when "size" attribute or "position" css rule is applied

### ISSUE THREAD

**Issue by nickland** [FortAwesome/angular-fontawesome#341]
### Describe the problem

When wrapping a div around a chevron right or chevron left and then giving that div "position absolute", the chevron left and right will just turn into "times" (the X symbol). This only happens if I use the "size" attribute on both elements. If you remove the size from ONE of the elements, it works just fine again but the other element just disappears. If you keep the size on both but remove the position absolute on the wrapper (or the element itself, this actually does not matter) the icons return to normal. I am so baffled by this.

### What did you expect?
Nothing, just the css rule of "position absolute" to apply. Instead this happened and threw me off guard completely.

### Reproducible test case
https://stackblitz.com/edit/angular-ivy-ywwfur?file=src/app/app.component.html

Do the following things to mess around with it, might help understand the issue more. Each point in this list assumes you started from the default state of the stackblitz I linked.
- Put one of the icons to size 3x leave the other at 4x -> The icons become "normal" again
- Remove the position absolute from the wrapper div -> The icons become normal again
- Remove the icon-wrapper div from both fa-icon elements and instead give the fa-icon element the position absolute -> The same issue will occur.
- Remove the size attribute from ONE of the elements -> The icons become "normal" again

**Comment by nickland** [comment]
If they have the same 'size' attribute, this just happens in general.

**Comment by devoto13** [comment]
> Nothing, just the css rule of "position absolute" to apply. Instead this happened and threw me off guard completely.

Well, it does exactly that. It takes your two icons and puts them on top of each other in the top right corner of the `.wrapper` element (thanks to the interaction of `position: absolute` with the `position: relative` on the parent element). This is what I see by default, which works correctly:

<img width="56" alt="image" src="https://user-images.githubusercontent.com/823594/147810400-d669fa33-5031-4e43-a1a7-b77b4da775ba.png">

Changing size to 3x works exactly the same, just one icon is smaller:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/823594/147810444-67d94524-f83e-42e5-8db6-5036d0c1ca99.png">

In either case, I don't see any bugs with `angular-fontawesome`, but sounds like you have the wrong expectation about what the CSS/markup does. You can observe the same behavior by putting "1" and "2" text instead of icons. If you need general support with understanding CSS this issue tracker is not an appropriate place to ask such questions, consider searching for similar questions on StackOverflow or ask your own question there if it is still unclear.

**Comment by nickland** [comment]
> In either case, I don't see any bugs 

Are we just going to ignore that the entire icon changes to a whole different icon without you actually changing the icon.

**Comment by nickland** [comment]
Oh my god I thought the icons changed to "X". They are the same but on top of each other.

🤦🤦🤦🤦🤦
