### ISSUE TITLE
Cannot find icon

### ISSUE THREAD

**Issue by victorbadila** [FortAwesome/angular-fontawesome#358]
### Describe the problem

I am trying to use the `pen-to-square` icon from the pro library https://fontawesome.com/icons/pen-to-square?s=solid
I searched it in all installed packages, the best I could find is `square-pen`, but that's another one.

### What did you expect?

I expected to be able to import a font awesome icon in the module, then use it like this: `<fa-icon [icon]="['far', 'square-to-pen']"></fa-icon>`

### Reproducible test case

No test case since I can't get it to show at all.

**Comment by devoto13** [comment]
A reproducible test case is a code you have now that does not work. It helps us to help you as we can either point out the error there or confirm a bug instead of guessing.

On the guessing side:

1. What exactly is the error you see?
2. Have you installed `@fortawesome/pro-solid-svg-icons` or `@fortawesome/free-solid-svg-icons` v6+? As the icon is only available since v6.
3. Have you added the icon to the icon library as explained in the [documentation](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/icon-library.md)?

   ```ts
   import {
     FaIconLibrary,
     FontAwesomeModule,
   } from '@fortawesome/angular-fontawesome';
   import { faPenToSquare } from '@fortawesome/free-solid-svg-icons';

   @NgModule({ ... })
   export class AppModule {
     constructor(library: FaIconLibrary) {
       library.addIcons(faPenToSquare);
     }
   }
   ```

**Comment by victorbadila** [comment]
In the link I posted it says it was added since 1.0.0, and it was only last updated in 6.0.0. I have the pro libs but not v6 and unfortunately there are things stopping me from updating the packages further.

**Comment by devoto13** [comment]
I think the icon was renamed in v6 to the new name. In v5 it's called `edit`, I think that's why it says "Added in 1.0.0" and "Changed in 6.0.0".
There is also a version picker in the icon search which you could use to search icons specifically for the FA version you have.

**Comment by victorbadila** [comment]
You're right, it's called edit, that fixed it, thanks
