### ISSUE TITLE
how use FA 6.x icons?

### ISSUE THREAD

**Issue by pelnarp** [FortAwesome/angular-fontawesome#359]
Hi team,
according to the documentation v 6.x icons should be supported by FA version 10.x, is it correct?
How should the icons be imported? I do not seem to be able to find the new icons, such as circle-phone for example. Thanks!

**Comment by devoto13** [comment]
`circle-phone` is a Pro icon and requires the [Pro plan](https://fontawesome.com/plans) to use it. That may be the reason why you can't import it from the free package. If you have the Pro plan, make sure you have the v6 `pro` icon packages installed. You can also contract FontAwesome support at hello@fontawesome.com.

Otherwise, you can use the "Free" filter on the website to only search for free icons.

![image](https://user-images.githubusercontent.com/823594/161619359-d6f82f09-9c13-4fe3-8470-49dc6cdd8bb9.png)
