### ISSUE TITLE
Customized icons with PRO

### ISSUE THREAD

**Issue by wonaGuillermo** [FortAwesome/angular-fontawesome#434]
Hi, I understand that the [kits do not work well with Angular](https://github.com/FortAwesome/angular-fontawesome/issues/423) and my question is how to use custom icons if I can't use the kits but the PRO icons?

**Comment by devoto13** [comment]
Here is an [example](https://stackblitz.com/edit/angular-z8v4ux-i7gazy?file=src%2Fapp%2Fapp.module.ts). You could also check out https://github.com/FortAwesome/angular-fontawesome/issues/172.

**Comment by wonaGuillermo** [comment]
But that would not allow me to use the fontawesome site to upload my SVGs, I would have to do all the work from my Angular project or am I wrong?

If so, I lose one of the features for which I decided to pay for PRO.

**Comment by devoto13** [comment]
> But that would not allow me to use the fontawesome site to upload my SVGs, I would have to do all the work from my Angular project or am I wrong?

Yes, this suggestion is only applicable for icons defined in the code. 

I'm not sure what exactly is the problem you're facing. If the problem is specifically that custom icon definition is not assignable to `IconDefinition` type used by this library, you can workaround it in a similar fashion `faUser as IconDefinition` and use Kits.

If the problem is the bug in the Kit packages described in https://github.com/FortAwesome/angular-fontawesome/issues/423#issuecomment-1929690721, I would suggest to reach out to https://fontawesome.com/support and ask them to prioritise fixing the bug. I'm not an employee and I just maintain this open-source component, so not much I can do about it.

**Comment by wonaGuillermo** [comment]
Thanks, I will try the solution

**Comment by devoto13** [comment]
https://github.com/FortAwesome/angular-fontawesome/pull/436 and https://github.com/FortAwesome/angular-fontawesome/pull/436 should lift the limitations related to the custom icons in the `angular-fontawesome`. The remaining part is broken types in the Kit itself - let's track it in the https://github.com/FortAwesome/angular-fontawesome/issues/423.
