### ISSUE TITLE
[listItem]="true" should add 'fa-li' class to the <fa-icon> component, not the inner SVG

### ISSUE THREAD

**Issue by pathurs** [FortAwesome/angular-fontawesome#51]
Comparing adding class="fa-li" to <fa-icon> or using [listItem]="true", the icon becomes misaligned vertically:

```html
<ul class="nav flex-column fa-ul">
    <li class="nav-item">
        <a class="nav-link" [routerLink]="['/welcome']" routerLinkActive="active">
            <fa-icon icon="home" [listItem]="true"></fa-icon>
            Welcome
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" [routerLink]="['/devices']" routerLinkActive="active">
            <fa-icon icon="desktop-alt" class="fa-li"></fa-icon>
            Devices
        </a>
    </li>
</ul>
```

![image](https://user-images.githubusercontent.com/3084995/40752998-68cb926c-64b5-11e8-8c3f-85a38aaa5c1d.png)

**Comment by robmadole** [comment]
We might want to deprecate the `listitem` prop altogether (we plan to do this in [React](https://github.com/FortAwesome/react-fontawesome/issues/85) and [Vue](https://github.com/FortAwesome/vue-fontawesome/issues/61)). The CSS for this is dependent on `fa-ul` which means it needs to apply outside of the icon. And as you've discovered the `fa-li` needs to happen on the parent of the icon. [This was a shift that was made in version 5.0 of FA](https://fontawesome.com/how-to-use/web-fonts-with-css).

So...all that said. I'm not sure that any work should be done to fix this. We probably just need to update the documentation so that it illustrates how this is possible with this component.

**Comment by devoto13** [comment]
I'm pretty sure you can achieve same effect (vertically aligned icons) by using `[fixedWidth]="true"`.

@robmadole is there any reason to support a dedicated way for aligning icons in the <li> element, while there is a more generic way available?

**Comment by robmadole** [comment]
@devoto13 yeah, there is some special work that has gone into making `fa-ul` and `fa-li` work together and "do what you would expect". I remember Dave and I going back and forth for a few days as we cross-browser tested and really honed those. They are worthwhile to have but not worthwhile to support in the `angular-fontawesome` component.

**Comment by pathurs** [comment]
Is there a reason you can't add 'fa-li' to the host element? Is it something to do with how you're creating this package?

**Comment by robmadole** [comment]
It's not a pattern that we want to rely on @pathurs.
