### ISSUE TITLE
Load icons by passing the string name and prefix as parameter from the component ts file

### ISSUE THREAD

**Issue by rurziceanu** [FortAwesome/angular-fontawesome#71]
Hello,
I load the Icon name from the server, and pass it as a parameter..
Something like this:

src/app/app.component.ts

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  iconName: string = 'coffee';
  iconPrefix: string = 'fas'
}

and then in html

src/app/app.component.html

  <fa-icon [icon]="[iconPrefix , iconName]"></fa-icon>

This does not work as it does not accept strings as parameter. It throws an error
I looked in code but I cannot see how I can do this

it works only like this
<fa-icon [icon]="['fas', 'coffee']"></fa-icon>
but not by passig them from the component ts
<fa-icon [icon]="[iconPrefix , iconName]"></fa-icon>

How can I pass the icon name as parameter to the icon component?
Maybe I'm doing it all wrong?

Thank you

**Comment by devoto13** [comment]
This is because component only accepts fixed set of strings and not any string for icons name and prefix. If you use same types in your AppComponent properties the error should go away. 

```
import { IconPrefix, IconName } from '@fortawesome/fontawesome-svg-core';

export class AppComponent {
iconName: IconName = 'coffee';
iconPrefix: IconPrefix = 'fas'
}
```

**Comment by rurziceanu** [comment]
Great! thx for the help 👍

**Comment by devoto13** [comment]
Closing as issue seems to be resolved.

**Comment by GitHubish** [comment]
@devoto13 I'm doing the same thing globally but with the _tsconfig.json_ **strictTemplates** configuration I get an error because I'm doing `<fa-icon ['fal', item.icon]>` but `item.icon` is a string and not an `IconName`. Shouldn't the definition be more permissive to accept a string directly? thanks

**Comment by devoto13** [comment]
@GitHubish It can, but we don't want to do that, because it also means that users will not get any completion for the built-in icons which will significantly worsen the experience for the majority of users in favor of much less common use case.

It was previously discussed in https://github.com/FortAwesome/angular-fontawesome/issues/172 and https://github.com/FortAwesome/Font-Awesome/issues/16592, but so far we didn't manage to find a solution, which makes everybody happy.

For now, I would suggest either casting `item.icon` to `IconName` in TS code or using `$any(item.icon`) to opt-out of type-checking in the template.
