### ISSUE TITLE
Create icon component dynamically and append it to element 

### ISSUE THREAD

**Issue by rurziceanu** [FortAwesome/angular-fontawesome#72]
Hello,
I'm trying to create a dynamic icon component and append it to an element.

I have a directive that creates a badge with an icon on an element

import { icon } from '@fortawesome/fontawesome-svg-core';
import { FaIconComponent } from '@fortawesome/angular-fontawesome';

constructor(
    private viewContainerRef: ViewContainerRef,
    @Inject(ComponentFactoryResolver) private factoryResolver: ComponentFactoryResolver,
   private _elementRef: ElementRef)

/** Creates the badge element */
  private _createBadgeElement(): HTMLElement {
       const badgeElement = this._document.createElement('span');

      // factory comp resolver
      const factory = this.factoryResolver.resolveComponentFactory(FaIconComponent);

     // create component
      const _icon = this.viewContainerRef.createComponent(factory);
     // set content of the component
      _icon.instance.iconProp = faCoffee;
      _icon.instance.icon = icon({iconName: 'coffee', prefix: 'fas'});

     // append instance to element
     badgeElement.appendChild(_icon.location.nativeElement);

     this._elementRef.nativeElement.appendChild(badgeElement);
     return badgeElement;
}

// in the module I added FaIconComponent to entry components

I have no error, but the rendered result is this:

span id="mat-badge-content-18" class="mat-badge-content mat-badge-active">
          < fa-icon class="ng-fa-icon ng-star-inserted" ></ fa-icon>
</span

And as result nothing is set in the icon
I don't understand why this does not work? 

Thank you

**Comment by veluria** [comment]
I have a very similar issue where I'm adding an icon via `innerHtml` and nothing is being displayed. I guess the icon library doesn't detect this change. Can I somehow make it rescan the template for icons?

**Comment by robmadole** [comment]
@rurziceanu if you can provide a reproducible test case for this we can take a look. You can use 
https://stackblitz.com/edit/angular-z8v4ux to jump-start you.

**Comment by veluria** [comment]
@robmadole Not @rurziceanu, but here is an example of my issue, which should be pretty similar/related: https://stackblitz.com/edit/angular-7fiawb

**Comment by devoto13** [comment]
@veluria No, you can not do this because of how [Angular framework works](https://stackoverflow.com/questions/40473910/how-to-dynamically-add-innerhtml-with-angular-2-components). @rurziceanu's [approach](https://netbasal.com/dynamically-creating-components-with-angular-a7346f4a982d) is correct. 

The missing piece is that FaIconComponent renders icon on change of inputs, but Angular does not call `ngOnChanges` hook for component created dynamically, because there are not input bindings in this case. So you have to call this method dynamically to force icon rendering. [Here](https://stackblitz.com/edit/angular-z8v4ux-cbgknf) is working example.

**Comment by veluria** [comment]
@devoto13 Thanks a lot for the example.

**Comment by JesperBalslev** [comment]
This is my issue also, i tried looking at the working example, but does not work here.

I have an add button, which adds this icon dynamically:

```
<fa-layers class="fa-fw" *ngIf="b['duration']">
  <fa-icon [icon]="['fal', 'clock']"></fa-icon>
  <fa-layers-text [inverse]="true" content="{{ b['duration'] }}" style="color: white;" transform="shrink-10 down-11" style="font-weight:900"></fa-layers-text>
</fa-layers>
```
This works fine while testing, and live reloading etc. But when i go to build with --prod, all other font awesome icons work fine, but the ones i add like this... does not.

I tried to add detectChanges to my method, kinda like in the example. But no changes.

```
constructor(public cd: ChangeDetectorRef) {

}

 addIcon(prog: Block) {
    // adding to array which i *ngFor in my .html file... the div is added, but the icon is not. :(
    this.cd.detectChanges();
  }
```
Any advice would be helpful!§

**Comment by devoto13** [comment]
I've been looking into this issue and I don't think that there is anything to fix on the `angular-fontawesome` side.

The key problem is that Angular does not have a built-in way to dynamically render component with inputs or outputs. Neither [`ngComponentOutlet` directive](https://angular.io/api/common/NgComponentOutlet), nor using [`ComponentFactoryResolver`](https://angular.io/api/core/ComponentFactoryResolver) directly supports it. You can try upvoting https://github.com/angular/angular/issues/15360 if you need this feature.

This leaves you with two good options:

1. Static rendering using `*ngIf` or similar directives. You can use this if you know all possible components beforehand. It will wire up inputs/outputs and change detection correctly using Angular itself.

    ```html
    <fa-icon *ngIf="shouldRenderFaIcon" icon="user"></fa-icon>
    <something-else *ngIf="shouldRenderSomethingElse" customInput="someInput"></something-else>
    ```
2. Third-party library, which supports rendering of dynamic components with inputs or outputs. One example of such library is mentioned in https://github.com/angular/angular/issues/15360#issuecomment-322851135. Here is [demo](https://stackblitz.com/edit/angular-z8v4ux-9sgfk4).

---

The approach, which I showed in https://github.com/FortAwesome/angular-fontawesome/issues/72#issuecomment-408473472, using `ComponentFactoryResolver` and manually calling `ngOnchanges({})` relies on the implementation detail of the component and may break in one of the future releases. While it is an attractive alternative to including another library it is not officially supported and may (although unlikely) break in the future.

---

@JesperBalslev I don't think your problem is related to this issue looking at the code you provided. Please open a new issue with the reproduction if you still experience the problem.

**Comment by imtDeveloper** [comment]
I know this was just closed, but I wanted to add that @rurziceanu's original code has more settings on the instance than is necessary. Instead of setting both iconProp and icon (the former being set to a static imported reference), you can simply set iconPrep as follows (using the coffee example):

`
 _icon.instance.iconProp = 'coffee';
`
or
`
 _icon.instance.iconProp = ['fas','coffee']; // make sure the prefix is the first of the two elements
`

This way you don't need to import the faCoffee definition. Also, you then don't need:
`
import { icon } from '@fortawesome/fontawesome-svg-core';
`

**Comment by Trapulo** [comment]
Hi I need something similar to render an icon as a pipe. With FA 4 I can just bind an innerHtml to string rendered by the pipe's transform function, but with FA5 I cannot find the solution.. someone can help me?

thanks

**Comment by devoto13** [comment]
@Trapulo You can do the same with FA 5. It's basically what `fa-icon` does under the hood. See [here](https://github.com/FortAwesome/angular-fontawesome/blob/master/src/lib/icon/icon.component.ts#L67), [here](https://github.com/FortAwesome/angular-fontawesome/blob/master/src/lib/icon/icon.component.ts#L126) and [here](https://github.com/FortAwesome/angular-fontawesome/blob/master/src/lib/icon/icon.component.ts#L136). `icon` function from `@fortawesome/fontawesome-svg-core` package can transform icon name into SVG string.

**Comment by Trapulo** [comment]
thank you!

constructor(private sanitizer: DomSanitizer) { }
...

 var outIcon = (value ? icon({ prefix: "fas", iconName: "smile" }) : icon({ prefix: "fas", iconName: "frown" }));
        var renderedIconHTML = this.sanitizer.bypassSecurityTrustHtml(
          outIcon.html.join('\n')
        );
        return renderedIconHTML;

**Comment by damienwebdev** [comment]
@devoto13 I'd be willing to submit a PR to address this issue. I think we could definitely achieve this without having to call `ngOnChanges`, additionally, we could also make the component `ChangeDetectionStrategy.onPush` for an additional performance gain. 

Do you think it would be worthwhile to do so?

**Comment by devoto13** [comment]
> I think we could definitely achieve this without having to call `ngOnChanges`

@damienwebdev I doubt that it is possible, but would be happy to review a PR if you manage to achieve it. This is worthwhile as it will make it easier for people to render the icon dynamically.

> additionally, we could also make the component `ChangeDetectionStrategy.onPush` for an additional performance gain

This is good on it's own. PR is welcome even without the first part!

**Comment by JohnnyDevNull** [comment]
Here if anyone needs this too. I run in this issue today... thanks to @kgrvr  for the hint!

```
        const factory = this.resolver.resolveComponentFactory(FaIconComponent);
        const faIcon = this.vcr.createComponent(factory);
        faIcon.instance.iconProp = faEdit;
        faIcon.instance.icon = icon({ iconName: 'edit', prefix: 'fas' });
        faIcon.instance.ngOnChanges({});
```

**Comment by jaws97** [comment]
I know this is closed, but still I was not able to get my solution so asking this question.

I'm having a table this gets rendered when the page loads and each column has unique ID  while I was using normal javascript and jquery in html i used document.getElementByID('columnID') and use .innnerHTML +=<img src=....><i class="fa fa-minus-circle">

Now I'm shifting my application to angular if I'm using innerHTML it is not getting rendered. The above solutions helped me create a dynamic icon but my requirement is that an  image should be there followed by minus icon and enclosed in a label.

My function is if someone clicks minus icon I hide the image.

**Comment by devoto13** [comment]
@jaws97 I guess you want to create your own component, which will include all the markup you need (including the icon) and render it dynamically. I would recommend to use StackOverflow if you need further help though as this is not an issue with `angular-fontawesome`, but rather question of rendering arbitrary markup dynamically in Angular.

**Comment by JohnnyDevNull** [comment]
> I know this is closed, but still I was not able to get my solution so asking this question.
> 
> I'm having a table this gets rendered when the page loads and each column has unique ID while I was using normal javascript and jquery in html i used document.getElementByID('columnID') and use .innnerHTML +=`<img src=.... alt="some image"> <i class="fa fa-minus-circle">`
> 
> Now I'm shifting my application to angular if I'm using innerHTML it is not getting rendered. The above solutions helped me create a dynamic icon but my requirement is that an image should be there followed by minus icon and enclosed in a label.
> 
> My function is if someone clicks minus icon I hide the image.

That kind of question should be postet at stack overlfow, not here in github where bugs and so on will be issued.
