### ISSUE TITLE
@fontawesome/schematics

### ISSUE THREAD

**Issue by oleksiipotiekhin** [FortAwesome/angular-fontawesome#83]
**Describe the solution you'd like:**
Is there a possibility to add **@fontawesome/schematics** for angular? To use `ng add fontawesome` or `ng add @fontawesome/schematics` to combine fontawesome and angular. It will improve integration experience.

**Comment by devoto13** [comment]
I would prefer this to be a part of this repo instead of a separate package, so the command would be:

    ng add @fortawesome/angular-fontawesome

For the initial version I would expect it to add `@fortawesome/fontawesome-svg-core`, `@fortawesome/free-solid-svg-icons` (and potentially other free packages) and `@fortawesome/angular-fontawesome` packages to the dependencies and import `FontAwesomeModule` into `AppModule`. Once this is in place we can discuss adding more options and customizations.

This [article](https://nitayneeman.com/posts/making-an-addable-angular-package-using-schematics/#adding-a-schematic) looks useful.

PS If somebody starts working on this, please post here, so effort is not duplicated.

**Comment by thanhpd** [comment]
Is anyone working on this feature? If not, I can take a look at this

**Comment by devoto13** [comment]
@thanhpd I did a good chunk of work in https://github.com/devoto13/angular-fontawesome/tree/schematics some time ago. So you can use it as a base. 

You can run tests using `yarn test:schematics`.

IIRC I didn't figure out an easy way to run this on the actual project. So the remaining work would be to sort it out and test, that it works with `ng add`. And from the plan outline above I think it is still does not add `FontAwesomeModule` to the application's `AppModule`.

Let me know if you need any help with it.

**Comment by Destreyf** [comment]
Another feature that could be implemented is prompts, so you could ask the users which fonts they wanted and i believe you can do a checkbox style input on the ng architect api.  This way packages that the user doesn't intend to use won't be pulled in automatically.
