### ISSUE TITLE
Icon grid

### ISSUE THREAD

**Issue by cutepanda12** [FortAwesome/angular-fontawesome#91]
Is there a way to show all icons in a grid/table on a page?

**Comment by robmadole** [comment]
@cutepanda12 I'm not sure what you mean. Are you asking if there is some mechanism that is part of `angular-fontawesome` that will do this for you? Maybe you just need a [list of icons](http://fontawesome.com/icons)?

**Comment by MaklaCof** [comment]
Probably the user want to show all icons to the user. I need something similar, so user can choose own icons.

I had an idea to show user all icons that are added to library. Can I get all icons that were added to library?
```
import { library } from "@fortawesome/fontawesome-svg-core";

//Solid
library.add(fas.faInfoSquare, fas.faExclamationTriangle, fas.faTimesCircle);
//Light
library.add(fal.faHome, fal.faChartPie, fal.faFileAlt, fal.faAsterisk);
```

I think this would also answer @cutepanda12 question.

**Comment by MaklaCof** [comment]
I have a scenario where user can add own custom shortcuts on dashboard (home page). Adding just text doesn't look so awesome. Much more awesome would be if there is also an icon.

I want to show user all icons I import, so it can choose one. This seems to me an easy solution, since all icons that were added to library are in final bundle and so at disposal to the user.

**Comment by cutepanda12** [comment]
![image](https://user-images.githubusercontent.com/42588922/45166207-7934a600-b1c4-11e8-8cce-861dc9377c0f.png)

I just want something similar to the site (attached image) so user can select it without having to click on a button to show the popup dialog in angular 4/5

**Comment by robmadole** [comment]
> @MaklaCof Icons are stored in library.definitions property. This is not present in TypeScript type definitions though. Maybe it worths to expose it. @robmadole what do you think?

@devoto13 off the cuff I agree with you ("better to create a separate array variable in your service/component"). This seems like a special use case and it's pretty trivial to implement and have ownership over it in the app.

@cutepanda12 I think you'll have to build that yourself...

**Comment by devoto13** [comment]
@cutepanda12 as @robmadole said, you'll have to build it yourself.

@MaklaCof I still think that it is a bad idea. Think about the case when your user have used `faCoffee` icon in their dashboard and than you decided that you don't need this icon in your application anymore and simply removed it from the `library`. Your user's dashboard will get broken because of change to the completely different part of the application. Anyway if you want to expose `Library.definitions` in TypeScript type definitions, please, open a new issue in the [umbrella project](https://github.com/FortAwesome/Font-Awesome) as this is not part of `angular-fontawesome`, but part of the `fontawesome-svg-core` package.
