### ISSUE TITLE
0.2.0 overwrites class on fa-layers component

### ISSUE THREAD

**Issue by SeriousLemon** [FortAwesome/angular-fontawesome#98]
### Describe the problem

Prior to 0.2.0 any classes on fa-layers were preserved. Now they are overwritten.

### What did you expect?

Classes should not be overwritten.

### Reproducible test case

https://stackblitz.com/edit/angular-z8v4ux-vvutjk

**Comment by toverux** [comment]
Yes! Same problem here.

`FaLayersComponent` has a `HostBinding` on `class`, and this takes control of the whole className string. Angular does *not* give different context to the components that are interested in the property.

This is discussed in https://github.com/angular/angular/issues/7289, where there are a few proposed workarounds, the following ones seem good: 
 - using NgClass https://github.com/angular/angular/issues/7289#issuecomment-352178875
 - mixing the HostBinding with an Input : https://github.com/angular/angular/issues/7289#issuecomment-390415535

**Comment by devoto13** [comment]
@toverux the latter approach looks good! 

If anybody is willing to submit a PR I would be happy to review it. Otherwise I'll have time to work on this early next week. Please add tests to make sure these 3 syntaxes work correctly: `[class]="my-class"`, `[class.my-class]="true"` and `[ngClass]="{'my-class': true}"` with the component.
